title: Donghoon's Blog
author: Donghoon Shin
description: >-
  A blog on Human-Computer Interaction research and design.

# This is CRITICAL for deploying to a subdirectory like /blog
url: "https://donghoon.io" # the base hostname & protocol for your site
baseurl: "/blog" # the subpath of your site, e.g. /blog

permalink: /:year:month:day_:title/

# You can add social links here to use in the footer later
twitter_username: your_twitter
github_username:  your_github

# Build settings
theme: minima # You can leave this, it won't be used since we made our own layout
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"